---
- name: Install Multiple packages
  hosts: web1
  tasks:
  - name: Install latet sudo
    yum:
      name: sudo
      state: latest
  - name: Install vsftpd package    
    yum:
      name:  vsftpd-2.2.2
      state: present
      allow_downgrade: yes
