---
- name: Install nginx and enable service on boot
  hosts: web1
  tasks: 
  - name: Install nginx
    yum:
      name: nginx
      state: present
  - name: Start and enable service on boot
    service: 
      name: nginx
      state: started
      enabled: yes
